name: celebut
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  loading_animation_widget: ^1.2.0+4
  flutter_portal: ^1.1.4
  overlay_support: ^2.1.0
  smooth_page_indicator: ^1.2.0+3
  pinput: ^5.0.0
  flutter_svg: ^2.0.7
  video_player: ^2.9.3
  

  # state management
  hooks_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1

  # routing
  go_router: ^14.2.1

  #
  firebase_core: ^3.4.0

  # splash
  flutter_native_splash: ^2.4.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  freezed: ^2.4.5
  json_serializable: ^6.6.1
  build_runner: ^2.4.6


# splash screen package
flutter_native_splash:
  background_image: "assets/images/bg.png"
  image: "assets/images/logo.png"
  ios: true
  android: true

android_12:
  image: "assets/images/logo.png"
  background_image: "assets/images/bg.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
  
