FROM golang:1.18.0-buster as builder

RUN apt-get -y update \
    && apt-get -y upgrade \
    && apt-get -y install git bash make gcc musl-dev

# Enables go modules
ENV GO111MODULE=on

WORKDIR /app

COPY Makefile go.mod go.sum ./

COPY . ./

RUN make tools

RUN make build-static

# Stage to run application with recompiling in fly
FROM builder as application
ARG PORT
ARG APP_PORT

CMD gin --port ${PORT} --appPort ${APP_PORT} --immediate --build cmd/celebutapi run main.go