package constants

const (
	UserTokenNotSuccessfullySent          = "user token not successfully sent"
	UserTokenSuccessfullySent             = "user token successfully sent"
	BusinessTokenNotSuccessfullySent      = "business token not successfully sent"
	BusinessTokenSuccessfullySent         = "business token successfully sent"
	PhoneNumberConfirmedSuccessFully      = "phone number confirmed successfully"
	PhoneNumberAlreadyConfirmed           = "phone number already confirmed"
	LoginSuccessful                       = "login successful"
	PasswordTokenSuccessfullySent         = "password token successfully sent"
	PasswordResetSuccessful               = "password reset successful"
	PasswordChangedSuccessfully           = "password changed successfully"
	AreaOfInterestsAddedSuccessfully      = "area of interests added successfully"
	AreaOfInterestAddedSuccessfully       = "area of interest added successfully"
	LanguageAddedSuccessfully             = "Language added successfully"
	NotificationPreferenceSetSuccessfully = "notification preference set successfully"
	UserProfileSuccessfullyUploaded       = "user profile picture successfully uploaded"
	UserProfileSuccessfullyUpdated        = "user profile successfully updated"
	UserProfilesSuccessfullyFetched       = "user profiles successfully fetched"
	UserSuccessFullyFetched               = "user successfully fetched"
	FollowerSuccessFullyFetched           = "follower successfully fetched"
	UserFollowedSuccessfully              = "user followed successfully"
	CelebrationCreatedSuccessfully        = "celebration created successfully"
	UserUnFollowedSuccessfully            = "user un-followed successfully"
	FollowersFetchedSuccessfully          = "followers fetched successfully"
	UserAlreadyBlocked                    = "user already blocked"
	UserBlockedSuccessfully               = "user blocked successfully"
	BlockedUsersFetchedSuccessfully       = "blocked users fetched successfully"
	UserUnBlockedSuccessfully             = "user unblocked successfully"
	FriendsFetchedSuccessfully            = "friends fetched successfully"
	ContentSettingsSetSuccessfully        = "content settings set successfully"
	CelebrationsFetchedSuccessfully       = "celebrations fetched successfully"
	CelebrationFetchedSuccessfully        = "celebration fetched successfully"
	CelebrationAcceptedSuccessfully       = "celebration accepted successfully"
	CelebrationDeclinedSuccessfully       = "celebration declined successfully"
)
