// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/confirm-phone": {
            "patch": {
                "description": "Confirm User Phone",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Confirm User Phone",
                "parameters": [
                    {
                        "description": "data to confirm user's phone",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.ConfirmPhoneNumber"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/dtos.ResponseObject"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Signs admin user in",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Signs user in",
                "parameters": [
                    {
                        "description": "user's email and password",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SignInDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dtos.ResponseObject"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.AuthenticatedUser"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/auth/reset-password": {
            "post": {
                "description": "Sends User Password Reset Link",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Send Password Reset Link",
                "parameters": [
                    {
                        "description": "data to send user password reset link",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.Email"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/dtos.ResponseObject"
                        }
                    }
                }
            },
            "patch": {
                "description": "Resets User Password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Password Reset",
                "parameters": [
                    {
                        "description": "data to reset user's password",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ResetPasswordDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/dtos.ResponseObject"
                        }
                    }
                }
            }
        },
        "/auth/self": {
            "get": {
                "description": "Gets Logged In user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Gets Logged In user",
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/dtos.ResponseObject"
                        }
                    }
                }
            }
        },
        "/auth/sign-up/business": {
            "post": {
                "description": "Signs Business up",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Signs Business up",
                "parameters": [
                    {
                        "description": "business' sign up data object",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.BusinessSignUp"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/dtos.ResponseObject"
                        }
                    }
                }
            }
        },
        "/auth/sign-up/user": {
            "post": {
                "description": "Signs user up",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Signs user up",
                "parameters": [
                    {
                        "description": "user's sign up data object",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UserSignUp"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/dtos.ResponseObject"
                        }
                    }
                }
            }
        },
        "/users/add-profile-image": {
            "put": {
                "description": "Add User Profile Picture",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Add User Profile Picture",
                "parameters": [
                    {
                        "description": "data to add user profile picture",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UploadImage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/dtos.ResponseObject"
                        }
                    }
                }
            }
        },
        "/users/update-profile": {
            "put": {
                "description": "Updates user information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update user information",
                "parameters": [
                    {
                        "description": "data to update user personal info ",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateUserProfile"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "$ref": "#/definitions/dtos.ResponseObject"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/wallets": {
            "get": {
                "description": "Get User Wallet with user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallet"
                ],
                "summary": "Get User Wallet with balance",
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dtos.ResponseObject"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtos.Wallet"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "constants.HttpStatus": {
            "type": "string",
            "enum": [
                "bad-request",
                "server-error",
                "success",
                "resource-not-found",
                "invalid-token",
                "token-found"
            ],
            "x-enum-varnames": [
                "HttpStatusBadRequest",
                "HttpStatusServerError",
                "HttpStatusSuccess",
                "HttpStatusResourceNotFound",
                "HttpStatusInvalidToken",
                "HttpStatusTokenNotFound"
            ]
        },
        "constants.IndustryType": {
            "type": "string",
            "enum": [
                "entertainment",
                "agriculture",
                "finance",
                "mining",
                "information-technology",
                "furniture"
            ],
            "x-enum-varnames": [
                "IndustryTypeEntertainment",
                "IndustryTypeAgriculture",
                "IndustryTypeFinance",
                "IndustryTypeMining",
                "IndustryTypeInformationTechnology",
                "IndustryTypeFurniture"
            ]
        },
        "dtos.BusinessSignUp": {
            "type": "object",
            "required": [
                "business_name",
                "country_code",
                "email",
                "industry",
                "password",
                "phone_number",
                "username"
            ],
            "properties": {
                "business_name": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 3
                },
                "country_code": {
                    "type": "string",
                    "maxLength": 3,
                    "minLength": 2
                },
                "email": {
                    "type": "string"
                },
                "industry": {
                    "$ref": "#/definitions/constants.IndustryType"
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "dtos.ConfirmPhoneNumber": {
            "type": "object",
            "required": [
                "phone_number",
                "token"
            ],
            "properties": {
                "phone_number": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "dtos.Email": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "dtos.ResponseObject": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/constants.HttpStatus"
                }
            }
        },
        "dtos.UpdateUserProfile": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                },
                "date_of_birth": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                }
            }
        },
        "dtos.UploadImage": {
            "type": "object",
            "required": [
                "image"
            ],
            "properties": {
                "image": {
                    "$ref": "#/definitions/multipart.FileHeader"
                }
            }
        },
        "dtos.UserSignUp": {
            "type": "object",
            "required": [
                "country_code",
                "date_of_birth",
                "email",
                "full_name",
                "password",
                "phone_number",
                "username"
            ],
            "properties": {
                "country_code": {
                    "type": "string",
                    "maxLength": 3,
                    "minLength": 2
                },
                "date_of_birth": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "dtos.Wallet": {
            "type": "object",
            "properties": {
                "available_balance": {
                    "type": "integer"
                },
                "balance_id": {
                    "type": "string"
                },
                "change_amount": {
                    "type": "integer"
                },
                "currency": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "locked_amount": {
                    "type": "integer"
                },
                "owner_id": {
                    "type": "string"
                },
                "owner_type": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.AuthenticatedUser": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "models.ResetPasswordDto": {
            "type": "object",
            "required": [
                "email",
                "password",
                "token"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "models.SignInDto": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "fcm_token": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "account_type": {
                    "type": "string"
                },
                "business_name": {
                    "type": "string"
                },
                "completion_state": {
                    "type": "integer"
                },
                "country_code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "date_of_birth": {
                    "type": "string"
                },
                "device_type": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "industry_type": {
                    "type": "string"
                },
                "interests": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ip_address": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "next_login_at": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "profile_image_url": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "verification_status": {
                    "type": "string"
                }
            }
        },
        "multipart.FileHeader": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string"
                },
                "header": {
                    "$ref": "#/definitions/textproto.MIMEHeader"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "textproto.MIMEHeader": {
            "type": "object",
            "additionalProperties": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
