definitions:
  constants.HttpStatus:
    enum:
    - bad-request
    - server-error
    - success
    - resource-not-found
    - invalid-token
    - token-found
    type: string
    x-enum-varnames:
    - HttpStatusBadRequest
    - HttpStatusServerError
    - HttpStatusSuccess
    - HttpStatusResourceNotFound
    - HttpStatusInvalidToken
    - HttpStatusTokenNotFound
  constants.IndustryType:
    enum:
    - entertainment
    - agriculture
    - finance
    - mining
    - information-technology
    - furniture
    type: string
    x-enum-varnames:
    - IndustryTypeEntertainment
    - IndustryTypeAgriculture
    - IndustryTypeFinance
    - IndustryTypeMining
    - IndustryTypeInformationTechnology
    - IndustryTypeFurniture
  dtos.BusinessSignUp:
    properties:
      business_name:
        maxLength: 200
        minLength: 3
        type: string
      country_code:
        maxLength: 3
        minLength: 2
        type: string
      email:
        type: string
      industry:
        $ref: '#/definitions/constants.IndustryType'
      password:
        type: string
      phone_number:
        type: string
      username:
        maxLength: 50
        minLength: 3
        type: string
    required:
    - business_name
    - country_code
    - email
    - industry
    - password
    - phone_number
    - username
    type: object
  dtos.ConfirmPhoneNumber:
    properties:
      phone_number:
        type: string
      token:
        type: string
    required:
    - phone_number
    - token
    type: object
  dtos.Email:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  dtos.ResponseObject:
    properties:
      data: {}
      error: {}
      message:
        type: string
      status:
        $ref: '#/definitions/constants.HttpStatus'
    type: object
  dtos.UpdateUserProfile:
    properties:
      address:
        maxLength: 100
        minLength: 3
        type: string
      date_of_birth:
        type: string
      full_name:
        maxLength: 100
        minLength: 3
        type: string
    type: object
  dtos.UploadImage:
    properties:
      image:
        $ref: '#/definitions/multipart.FileHeader'
    required:
    - image
    type: object
  dtos.UserSignUp:
    properties:
      country_code:
        maxLength: 3
        minLength: 2
        type: string
      date_of_birth:
        type: string
      email:
        type: string
      full_name:
        maxLength: 100
        minLength: 3
        type: string
      password:
        type: string
      phone_number:
        type: string
      username:
        maxLength: 50
        minLength: 3
        type: string
    required:
    - country_code
    - date_of_birth
    - email
    - full_name
    - password
    - phone_number
    - username
    type: object
  dtos.Wallet:
    properties:
      available_balance:
        type: integer
      balance_id:
        type: string
      change_amount:
        type: integer
      currency:
        type: string
      id:
        type: string
      locked_amount:
        type: integer
      owner_id:
        type: string
      owner_type:
        type: string
      status:
        type: string
    type: object
  models.AuthenticatedUser:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
      user:
        $ref: '#/definitions/models.User'
    type: object
  models.ResetPasswordDto:
    properties:
      email:
        type: string
      password:
        type: string
      token:
        type: string
    required:
    - email
    - password
    - token
    type: object
  models.SignInDto:
    properties:
      email:
        type: string
      fcm_token:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.User:
    properties:
      account_type:
        type: string
      business_name:
        type: string
      completion_state:
        type: integer
      country_code:
        type: string
      created_at:
        type: string
      date_of_birth:
        type: string
      device_type:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      industry_type:
        type: string
      interests:
        items:
          type: string
        type: array
      ip_address:
        type: string
      last_name:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      next_login_at:
        type: string
      phone_number:
        type: string
      profile_image_url:
        type: string
      status:
        type: string
      updated_at:
        type: string
      username:
        type: string
      verification_status:
        type: string
    type: object
  multipart.FileHeader:
    properties:
      filename:
        type: string
      header:
        $ref: '#/definitions/textproto.MIMEHeader'
      size:
        type: integer
    type: object
  textproto.MIMEHeader:
    additionalProperties:
      items:
        type: string
      type: array
    type: object
info:
  contact: {}
paths:
  /auth/confirm-phone:
    patch:
      consumes:
      - application/json
      description: Confirm User Phone
      parameters:
      - description: data to confirm user's phone
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.ConfirmPhoneNumber'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/dtos.ResponseObject'
      summary: Confirm User Phone
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Signs admin user in
      parameters:
      - description: user's email and password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SignInDto'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/dtos.ResponseObject'
            - properties:
                data:
                  $ref: '#/definitions/models.AuthenticatedUser'
              type: object
      summary: Signs user in
      tags:
      - Auth
  /auth/reset-password:
    patch:
      consumes:
      - application/json
      description: Resets User Password
      parameters:
      - description: data to reset user's password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ResetPasswordDto'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/dtos.ResponseObject'
      summary: Password Reset
      tags:
      - Auth
    post:
      consumes:
      - application/json
      description: Sends User Password Reset Link
      parameters:
      - description: data to send user password reset link
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.Email'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/dtos.ResponseObject'
      summary: Send Password Reset Link
      tags:
      - Auth
  /auth/self:
    get:
      consumes:
      - application/json
      description: Gets Logged In user
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/dtos.ResponseObject'
      summary: Gets Logged In user
      tags:
      - Auth
  /auth/sign-up/business:
    post:
      consumes:
      - application/json
      description: Signs Business up
      parameters:
      - description: business' sign up data object
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.BusinessSignUp'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/dtos.ResponseObject'
      summary: Signs Business up
      tags:
      - Auth
  /auth/sign-up/user:
    post:
      consumes:
      - application/json
      description: Signs user up
      parameters:
      - description: user's sign up data object
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.UserSignUp'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/dtos.ResponseObject'
      summary: Signs user up
      tags:
      - Auth
  /users/add-profile-image:
    put:
      consumes:
      - application/json
      description: Add User Profile Picture
      parameters:
      - description: data to add user profile picture
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.UploadImage'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/dtos.ResponseObject'
      summary: Add User Profile Picture
      tags:
      - User
  /users/update-profile:
    put:
      consumes:
      - application/json
      description: Updates user information
      parameters:
      - description: 'data to update user personal info '
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.UpdateUserProfile'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/dtos.ResponseObject'
        "400":
          description: Invalid input
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Update user information
      tags:
      - User
  /wallets:
    get:
      consumes:
      - application/json
      description: Get User Wallet with user
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/dtos.ResponseObject'
            - properties:
                data:
                  $ref: '#/definitions/dtos.Wallet'
              type: object
        "400":
          description: Invalid input
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Get User Wallet with balance
      tags:
      - Wallet
swagger: "2.0"
