import React, { useState } from 'react';
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { aiService } from '../services/api'; import { useAuth } from '../auth/AuthContext';
import { AppIcon, Button, Card, Field, Heading, Screen, StatePanel } from '../components/ui/app-ui';
import { Radius, Spacing, Type } from '../constants/theme'; import { useAppTheme } from '../hooks/use-app-theme';

const suggestions = ['graduations this week', 'family celebrations', 'creative milestones'];
export default function ExploreScreen() {
  const { token } = useAuth(); const { colors } = useAppTheme(); const [query, setQuery] = useState(''); const [results, setResults] = useState([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [expanded, setExpanded] = useState('');
  const search = async (value = query) => { const clean = value.trim(); if (!clean) return; setQuery(clean); setLoading(true); setError(''); try { const response = await aiService.searchCelebrations(clean, 20, token); setResults(response.results || []); } catch (err) { setError(err.message || 'Search failed'); } finally { setLoading(false); } };
  const report = item => Alert.alert('Report this celebration?', 'Reports are private and reviewed by the safety team.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Send report', onPress: async () => { await aiService.logInteraction(item.celebration_id, 'report', { target_type: 'celebration', source: 'search' }, token); setResults(v => v.filter(x => x.celebration_id !== item.celebration_id)); } }]);
  const renderItem = ({ item }) => { const open = expanded === item.celebration_id; const score = Math.max(0, Math.min(100, Math.round((item.similarity_score || 0) * 100))); return <Pressable accessibilityRole="button" accessibilityState={{ expanded: open }} accessibilityLabel={`${item.message || 'Celebration'}. ${score} percent relevance.`} onPress={() => setExpanded(open ? '' : item.celebration_id)}><Card><View style={styles.resultTop}><View style={[styles.icon, { backgroundColor: colors.accentSoft }]}><AppIcon name={{ ios: 'sparkles', android: 'celebration', web: 'celebration' }} color={colors.accent} /></View><View style={styles.resultCopy}><Text style={[styles.resultTitle, { color: colors.text }]}>{item.message || 'Community celebration'}</Text><Text style={[styles.match, { color: colors.textSecondary }]}>Meaningful match · {score}% relevance</Text></View><AppIcon name={{ ios: open ? 'chevron.up' : 'chevron.down', android: open ? 'expand_less' : 'expand_more', web: open ? 'expand_less' : 'expand_more' }} color={colors.textSecondary} /></View>{open ? <View style={[styles.details, { borderTopColor: colors.border }]}><Text style={[styles.detailText, { color: colors.textSecondary }]}>This appeared because its meaning is close to “{query}”. Search ranking is not an endorsement or popularity score.</Text><Button label="Report celebration" variant="danger" onPress={() => report(item)} icon={{ ios: 'exclamationmark.bubble', android: 'report', web: 'report' }} /></View> : null}</Card></Pressable>; };
  return <Screen><Heading eyebrow="Semantic search" title="Search by meaning" description="Describe the kind of moment you’re looking for—plain language works best." /><View style={styles.searchRow}><View style={styles.searchField}><Field label="What would you like to find?" value={query} onChangeText={setQuery} onSubmitEditing={() => search()} returnKeyType="search" placeholder="For example, new beginnings" error={error ? `${error}. Check your connection and try again.` : undefined} /></View><View style={styles.searchButton}><Button label="Search" onPress={() => search()} loading={loading} disabled={!query.trim()} icon={{ ios: 'magnifyingglass', android: 'search', web: 'search' }} /></View></View>{!results.length && !loading && !error ? <View><Text style={[styles.suggestLabel, { color: colors.textSecondary }]}>Try one of these</Text><View style={styles.suggestions}>{suggestions.map(value => <Pressable key={value} accessibilityRole="button" onPress={() => search(value)} style={({ pressed }) => [styles.suggestion, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? .65 : 1 }]}><AppIcon name={{ ios: 'magnifyingglass', android: 'search', web: 'search' }} color={colors.primary} size={18} /><Text style={[styles.suggestionText, { color: colors.text }]}>{value}</Text></Pressable>)}</View><StatePanel icon={{ ios: 'text.magnifyingglass', android: 'manage_search', web: 'manage_search' }} title="Meaning, not exact words" message="Search understands related ideas, so “new beginnings” can find graduations, new jobs, or moving-day celebrations." /></View> : loading ? <StatePanel busy icon={{ ios: 'magnifyingglass', android: 'search', web: 'search' }} title="Looking across celebrations" message="Finding the closest meanings…" /> : !error && !results.length ? <StatePanel icon={{ ios: 'doc.text.magnifyingglass', android: 'search_off', web: 'search_off' }} title="No close matches yet" message="Try a broader idea or fewer details." action={<Button label="Clear search" variant="secondary" onPress={() => setQuery('')} />} /> : <FlatList data={results} keyExtractor={item => item.celebration_id} renderItem={renderItem} initialNumToRender={8} windowSize={7} contentContainerStyle={styles.list} />}</Screen>;
}
const styles = StyleSheet.create({ searchRow: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.sm }, searchField: { flex: 1 }, searchButton: { paddingTop: 27 }, suggestLabel: { fontSize: Type.label, fontWeight: '700', marginBottom: Spacing.sm }, suggestions: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm }, suggestion: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, paddingHorizontal: 12, borderRadius: Radius.pill, borderWidth: StyleSheet.hairlineWidth }, suggestionText: { fontSize: Type.caption, fontWeight: '700' }, resultTop: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md }, icon: { width: 48, height: 48, borderRadius: Radius.md, alignItems: 'center', justifyContent: 'center' }, resultCopy: { flex: 1 }, resultTitle: { fontSize: Type.body, fontWeight: '700', lineHeight: 23 }, match: { fontSize: Type.caption, marginTop: 4 }, details: { marginTop: Spacing.md, paddingTop: Spacing.md, borderTopWidth: StyleSheet.hairlineWidth, gap: Spacing.md }, detailText: { fontSize: Type.caption, lineHeight: 20 }, list: { paddingBottom: 120 } });
