import React, { useCallback, useEffect, useState } from 'react'; import { Alert, FlatList, StyleSheet, Text, View } from 'react-native'; import { useRouter } from 'expo-router';
import { useAuth } from '../auth/AuthContext'; import { moderationService } from '../services/api';
import { BackButton, Button, Card, Heading, Screen, StatePanel, StatusBanner } from '../components/ui/app-ui'; import { Spacing, Type } from '../constants/theme'; import { useAppTheme } from '../hooks/use-app-theme';
export default function ModerationScreen() {
  const { token, user } = useAuth(); const { colors } = useAppTheme(); const router = useRouter(); const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState(''); const allowed = user?.role === 'admin' || user?.role === 'moderator';
  const goBack = () => router.canGoBack() ? router.back() : router.replace('/you');
  const load = useCallback(async () => { if (!allowed) { setLoading(false); return; } setLoading(true); setError(''); try { const data = await moderationService.queue(token); setItems(Array.isArray(data) ? data : data.items || []); } catch (err) { setError(err.message || 'Queue could not be loaded'); } finally { setLoading(false); } }, [allowed, token]); useEffect(() => { let active = true; Promise.resolve().then(() => active && load()); return () => { active = false; }; }, [load]);
  const confirm = (item, decision) => Alert.alert(decision === 'approved' ? 'Approve this celebration?' : 'Reject this celebration?', decision === 'approved' ? 'It will become visible to the intended audience.' : 'It will stay hidden. Review the full context before rejecting.', [{ text: 'Cancel', style: 'cancel' }, { text: decision === 'approved' ? 'Approve' : 'Reject', style: decision === 'rejected' ? 'destructive' : 'default', onPress: () => decide(item.id, decision) }]);
  const decide = async (id, decision) => { setBusy(id); setError(''); try { await moderationService.resolve(id, decision, token); setItems(v => v.filter(item => item.id !== id)); } catch (err) { setError(`${err.message || 'Decision was not saved'}. The item remains in the queue; try again.`); } finally { setBusy(''); } };
  if (!allowed) return <Screen><BackButton onPress={goBack} /><StatePanel icon={{ ios: 'lock.shield', android: 'shield_lock', web: 'shield_lock' }} title="Moderator access only" message="This safety workspace is available only to approved moderators and administrators." /></Screen>;
  const renderItem = ({ item }) => <Card><Text style={[styles.content, { color: colors.text }]}>{item.flagged_content}</Text><View style={[styles.signal, { backgroundColor: colors.warningSoft }]}><Text style={[styles.signalText, { color: colors.warning }]}>Automated signal: {Math.round(Number(item.toxicity_score) * 100)}%</Text></View><Text style={[styles.note, { color: colors.textSecondary }]}>The automated score is context—not a verdict. Check intent, identity terms, quoted speech, and community impact before deciding.</Text><View style={styles.actions}><View style={styles.action}><Button label="Reject" variant="danger" loading={busy === item.id} onPress={() => confirm(item, 'rejected')} /></View><View style={styles.action}><Button label="Approve" loading={busy === item.id} onPress={() => confirm(item, 'approved')} /></View></View></Card>;
  return <Screen><BackButton onPress={goBack} /><Heading eyebrow="Moderator workspace" title="Safety review" description="Use context and community guidelines. Automated signals can be wrong." />{error ? <StatusBanner tone="error" title="Decision not saved" message={error} /> : null}{loading ? <StatePanel busy icon={{ ios: 'checklist', android: 'fact_check', web: 'fact_check' }} title="Loading review queue" message="Fetching pending items securely…" /> : <FlatList data={items} keyExtractor={item => item.id} renderItem={renderItem} onRefresh={load} refreshing={loading} initialNumToRender={8} windowSize={7} contentContainerStyle={styles.list} ListEmptyComponent={<StatePanel icon={{ ios: 'checkmark.shield', android: 'verified_user', web: 'verified_user' }} title="The queue is clear" message="There are no pending celebrations to review." action={<Button label="Refresh" variant="secondary" onPress={load} />} />} />}</Screen>;
}
const styles = StyleSheet.create({ content: { fontSize: Type.body, lineHeight: 25 }, signal: { alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, marginTop: Spacing.md }, signalText: { fontSize: Type.caption, fontWeight: '800' }, note: { fontSize: Type.caption, lineHeight: 20, marginTop: Spacing.md }, actions: { flexDirection: 'row', gap: Spacing.sm, marginTop: Spacing.lg }, action: { flex: 1 }, list: { paddingBottom: 120 } });
