import React, { useCallback, useState } from 'react';
import { FlatList, Linking, StyleSheet, Text, View } from 'react-native'; import * as Location from 'expo-location';
import { celebrationService } from '../services/api'; import { useAuth } from '../auth/AuthContext';
import { AppIcon, Button, Card, Heading, Screen, StatePanel, StatusBanner } from '../components/ui/app-ui'; import { Radius, Spacing, Type } from '../constants/theme'; import { useAppTheme } from '../hooks/use-app-theme';

export default function NearbyScreen() {
  const { token } = useAuth(); const { colors } = useAppTheme(); const [results, setResults] = useState([]); const [status, setStatus] = useState('intro'); const [error, setError] = useState('');
  const load = useCallback(async () => { setStatus('loading'); setError(''); try { const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== 'granted') { setStatus('denied'); return; } const { coords } = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); const data = await celebrationService.nearby(coords.latitude, coords.longitude, 50, token); setResults(Array.isArray(data) ? data : data.celebrations || []); setStatus('ready'); } catch (err) { setError(err.message || 'Location could not be loaded'); setStatus('error'); } }, [token]);
  const renderItem = ({ item }) => <Card><View style={styles.cardTop}><View style={[styles.pin, { backgroundColor: colors.primarySoft }]}><AppIcon name={{ ios: 'mappin', android: 'location_on', web: 'location_on' }} color={colors.primary} /></View><View style={styles.cardCopy}><Text style={[styles.title, { color: colors.text }]}>{item.caption || 'Community celebration'}</Text><Text style={[styles.distance, { color: colors.accent }]}>{Number(item.distance_km).toFixed(1)} km away · approximate</Text></View></View>{item.notes ? <Text style={[styles.notes, { color: colors.textSecondary }]}>{item.notes}</Text> : null}</Card>;
  return <Screen><Heading eyebrow="Nearby" title="Moments around you" description="Celebut uses your location once to find celebrations within 50 km. Your precise coordinates are never shown to other people." />{status === 'intro' ? <><StatusBanner tone="info" title="You stay in control" message="Location is requested only after you tap Continue. You can change access anytime in device Settings." /><StatePanel icon={{ ios: 'location.circle', android: 'my_location', web: 'my_location' }} title="See what’s happening nearby" message="We’ll use an approximate distance and won’t track you in the background." action={<Button label="Continue to location access" onPress={load} icon={{ ios: 'location', android: 'near_me', web: 'near_me' }} />} /></> : status === 'loading' ? <StatePanel busy icon={{ ios: 'location', android: 'near_me', web: 'near_me' }} title="Finding nearby moments" message="Using your current location for this search only…" /> : status === 'denied' ? <StatePanel icon={{ ios: 'location.slash', android: 'location_disabled', web: 'location_disabled' }} title="Location access is off" message="Nearby search needs foreground location. You can enable it in Settings, or keep using every other part of Celebut." action={<View style={styles.actions}><Button label="Open settings" onPress={() => Linking.openSettings()} /><Button label="Not now" variant="quiet" onPress={() => setStatus('intro')} /></View>} /> : status === 'error' ? <StatePanel icon={{ ios: 'wifi.exclamationmark', android: 'wifi_off', web: 'wifi_off' }} title="We couldn’t find nearby moments" message={`${error}. Check location services and your connection, then try again.`} action={<Button label="Try again" onPress={load} />} /> : <FlatList data={results} keyExtractor={item => item.id} renderItem={renderItem} initialNumToRender={8} windowSize={7} contentContainerStyle={styles.list} ListEmptyComponent={<StatePanel icon={{ ios: 'map', android: 'map', web: 'map' }} title="It’s quiet nearby" message="No active celebrations were found within 50 km. Try again later." action={<Button label="Refresh" variant="secondary" onPress={load} />} />} />}</Screen>;
}
const styles = StyleSheet.create({ cardTop: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md }, pin: { width: 48, height: 48, borderRadius: Radius.md, alignItems: 'center', justifyContent: 'center' }, cardCopy: { flex: 1 }, title: { fontSize: Type.heading, fontWeight: '700' }, distance: { fontSize: Type.caption, fontWeight: '700', marginTop: 4 }, notes: { fontSize: Type.body, lineHeight: 24, marginTop: Spacing.md }, list: { paddingBottom: 120 }, actions: { gap: Spacing.sm, minWidth: 240 } });
