import React, { useState } from 'react';
import { Alert, Pressable, StyleSheet, Switch, Text, View } from 'react-native'; import { useRouter } from 'expo-router';
import { useAuth } from '../auth/AuthContext'; import { AppIcon, Button, Card, Heading, Screen, StatusBanner } from '../components/ui/app-ui'; import { Radius, Spacing, Type } from '../constants/theme'; import { useAppTheme } from '../hooks/use-app-theme';

function Row({ icon, title, detail, onPress, danger }) { const { colors } = useAppTheme(); return <Pressable accessibilityRole="button" accessibilityLabel={title} accessibilityHint={detail} onPress={onPress} style={({ pressed }) => [styles.row, { opacity: pressed ? .6 : 1 }]}><View style={[styles.rowIcon, { backgroundColor: danger ? colors.dangerSoft : colors.primarySoft }]}><AppIcon name={icon} color={danger ? colors.danger : colors.primary} /></View><View style={styles.rowCopy}><Text style={[styles.rowTitle, { color: danger ? colors.danger : colors.text }]}>{title}</Text>{detail ? <Text style={[styles.rowDetail, { color: colors.textSecondary }]}>{detail}</Text> : null}</View><AppIcon name={{ ios: 'chevron.right', android: 'chevron_right', web: 'chevron_right' }} color={colors.textSubtle} size={18} /></Pressable>; }
function ToggleRow({ title, detail, value, onValueChange }) { const { colors } = useAppTheme(); return <View style={styles.toggleRow}><View style={styles.rowCopy}><Text style={[styles.rowTitle, { color: colors.text }]}>{title}</Text><Text style={[styles.rowDetail, { color: colors.textSecondary }]}>{detail}</Text></View><Switch accessibilityLabel={title} value={value} onValueChange={onValueChange} trackColor={{ false: colors.border, true: colors.accent }} thumbColor={colors.surfaceRaised} /></View>; }
export default function YouScreen() {
  const { user, logout } = useAuth(); const { colors, mode } = useAppTheme(); const router = useRouter(); const [section, setSection] = useState(''); const [likes, setLikes] = useState(true); const [nearby, setNearby] = useState(false); const [messages, setMessages] = useState(true); const canModerate = user?.role === 'admin' || user?.role === 'moderator';
  const signOut = () => Alert.alert('Sign out of Celebut?', 'Drafts saved on this device remain available when you return.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Sign out', style: 'destructive', onPress: logout }]);
  const toggle = name => setSection(current => current === name ? '' : name);
  return <Screen scroll><Heading eyebrow="Your space" title={user?.first_name || user?.username || 'You'} description={`@${user?.username || 'member'} · ${user?.email || 'Signed in securely'}`} />
    <Card><View style={styles.profile}><View style={[styles.avatar, { backgroundColor: colors.primary }]}><Text style={[styles.initial, { color: colors.onPrimary }]}>{(user?.first_name || user?.username || 'Y')[0].toUpperCase()}</Text></View><View style={styles.profileCopy}><Text style={[styles.profileName, { color: colors.text }]}>{[user?.first_name, user?.last_name].filter(Boolean).join(' ') || user?.username || 'Celebut member'}</Text><Text style={[styles.profileMeta, { color: colors.textSecondary }]}>Role: {user?.role || 'member'} · {mode} appearance</Text></View></View></Card>
    {canModerate ? <><Text style={[styles.sectionTitle, { color: colors.textSecondary }]}>MODERATION</Text><Card><Row icon={{ ios: 'checkmark.shield', android: 'verified_user', web: 'verified_user' }} title="Safety review queue" detail="Review celebrations held for human moderation" onPress={() => router.push('/moderation')} /></Card></> : null}
    <Text style={[styles.sectionTitle, { color: colors.textSecondary }]}>PREFERENCES</Text><Card>
      <Row icon={{ ios: 'bell', android: 'notifications', web: 'notifications' }} title="Notifications" detail="Choose which updates deserve your attention" onPress={() => toggle('notifications')} />
      {section === 'notifications' ? <View style={[styles.panel, { borderTopColor: colors.border }]}><ToggleRow title="Celebration activity" detail="Likes, replies, and mentions" value={likes} onValueChange={setLikes} /><ToggleRow title="Messages and followers" detail="Direct messages and new followers" value={messages} onValueChange={setMessages} /><ToggleRow title="Nearby suggestions" detail="Off by default; does not enable background tracking" value={nearby} onValueChange={setNearby} /><StatusBanner tone="info" title="Quiet by design" message="Push preferences save when the backend settings endpoint is connected. Nearby alerts never reveal your precise location." /></View> : null}
      <Row icon={{ ios: 'person.crop.circle', android: 'manage_accounts', web: 'manage_accounts' }} title="Profile and interests" detail="Name, photo, bio, and recommendation interests" onPress={() => toggle('profile')} />
      {section === 'profile' ? <View style={[styles.panel, { borderTopColor: colors.border }]}><Text style={[styles.panelText, { color: colors.textSecondary }]}>Profile editing is managed by the existing profile API. Your interests influence recommendations; they are not used to rank your worth or popularity.</Text><Button label="Profile editor coming soon" variant="secondary" disabled onPress={() => {}} /></View> : null}
      <Row icon={{ ios: 'wallet.pass', android: 'account_balance_wallet', web: 'account_balance_wallet' }} title="Wallet" detail="View balances and celebration activity" onPress={() => toggle('wallet')} />
      {section === 'wallet' ? <View style={[styles.panel, { borderTopColor: colors.border }]}><Text style={[styles.panelText, { color: colors.textSecondary }]}>Wallet actions remain protected by the existing backend. Financial controls will appear here once the account endpoints are exposed to mobile.</Text></View> : null}
    </Card>
    <Text style={[styles.sectionTitle, { color: colors.textSecondary }]}>PRIVACY & SAFETY</Text><Card><Row icon={{ ios: 'hand.raised', android: 'privacy_tip', web: 'privacy_tip' }} title="Privacy and location" detail="Foreground-only location and data choices" onPress={() => toggle('privacy')} />{section === 'privacy' ? <View style={[styles.panel, { borderTopColor: colors.border }]}><Text style={[styles.panelText, { color: colors.textSecondary }]}>Celebut requests location only when you use Nearby or submit a celebration. Precise coordinates are sent securely for distance calculations and are never displayed to other members.</Text></View> : null}<Row icon={{ ios: 'person.crop.circle.badge.xmark', android: 'block', web: 'block' }} title="Blocked accounts" detail="People you block are not notified" onPress={() => toggle('blocked')} />{section === 'blocked' ? <View style={[styles.panel, { borderTopColor: colors.border }]}><Text style={[styles.panelText, { color: colors.textSecondary }]}>Blocked-account management will appear here when the existing block-list endpoint is connected. You can already block people from their recommendation card.</Text></View> : null}<Row icon={{ ios: 'exclamationmark.bubble', android: 'report', web: 'report' }} title="Reporting and support" detail="Private reports and community safety help" onPress={() => toggle('report')} />{section === 'report' ? <View style={[styles.panel, { borderTopColor: colors.border }]}><Text style={[styles.panelText, { color: colors.textSecondary }]}>Reports are private. For immediate danger, contact local emergency services; Celebut moderation is not an emergency response service.</Text></View> : null}</Card>
    <View style={styles.danger}><Button label="Sign out" variant="danger" onPress={signOut} icon={{ ios: 'rectangle.portrait.and.arrow.right', android: 'logout', web: 'logout' }} /></View>
  </Screen>;
}
const styles = StyleSheet.create({ profile: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md }, avatar: { width: 64, height: 64, borderRadius: 32, alignItems: 'center', justifyContent: 'center' }, initial: { fontSize: 26, fontWeight: '800' }, profileCopy: { flex: 1 }, profileName: { fontSize: Type.heading, fontWeight: '700' }, profileMeta: { fontSize: Type.caption, marginTop: 5 }, sectionTitle: { fontSize: 12, fontWeight: '800', letterSpacing: .8, marginTop: Spacing.md, marginBottom: Spacing.sm }, row: { minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: Spacing.md }, rowIcon: { width: 44, height: 44, borderRadius: Radius.md, alignItems: 'center', justifyContent: 'center' }, rowCopy: { flex: 1 }, rowTitle: { fontSize: Type.label, fontWeight: '700' }, rowDetail: { fontSize: Type.caption, lineHeight: 19, marginTop: 2 }, panel: { borderTopWidth: StyleSheet.hairlineWidth, paddingTop: Spacing.md, paddingBottom: Spacing.md, gap: Spacing.md }, panelText: { fontSize: Type.body, lineHeight: 24 }, toggleRow: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: Spacing.md }, danger: { marginTop: Spacing.lg, marginBottom: Spacing.xl } });
