app:
  name: 'celebut-api'
  version: '1.0.0'

http:
  port: '8080'
  service_address: ':8080'

logger:
  log_level: 'debug'
  rollbar_env: 'celebut-api'

postgres:
  pool_max: 2
  url: 'postgres://postgres:root@database:5432/celebut_db'
