// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/business/industry": {
            "get": {
                "security": [
                    {
                        "Auth-Token": []
                    }
                ],
                "description": "Get list of business industries",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Industries"
                ],
                "summary": "Get industries",
                "operationId": "industries-list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/business.getIndustryResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Auth-Token": []
                    }
                ],
                "description": "Create a new business industry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Industries"
                ],
                "summary": "Create industry",
                "operationId": "create-industry",
                "parameters": [
                    {
                        "description": "Create new industry",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/business.createIndustryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Industry"
                        }
                    }
                }
            }
        },
        "/celebrations": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get celebrations based on request type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Celebrations"
                ],
                "summary": "Get Celebrations",
                "operationId": "get-celebrations",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/celebrations.getCelebrationsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a celebration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Celebrations"
                ],
                "summary": "Create Celebration",
                "operationId": "create-celebration",
                "parameters": [
                    {
                        "description": "create a new celebration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/celebrations.createCelebrationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/celebrations.createCelebrationResponse"
                        }
                    }
                }
            }
        },
        "/celebrations/report/{celebrationID}": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Report a celebration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Celebrations"
                ],
                "summary": "Report celebration",
                "operationId": "report-celebration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "celebration identifier",
                        "name": "celebrationID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/celebrations.reportCelebrationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/celebrations/{celebrationID}": {
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Delete a celebration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Celebrations"
                ],
                "summary": "Delete Celebration",
                "operationId": "delete-celebration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "celebration identifier",
                        "name": "celebrationID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/celebrations.deleteCelebrationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/client": {
            "post": {
                "description": "Create a new client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "[Admin] Create a client",
                "operationId": "create-client",
                "parameters": [
                    {
                        "description": "Create a client",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.createRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.createResponse"
                        }
                    }
                }
            }
        },
        "/client/auth": {
            "post": {
                "description": "Authenticate a client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Authenticate a client",
                "operationId": "auth-client",
                "parameters": [
                    {
                        "description": "Authenticate a client",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.authRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.authResponse"
                        }
                    }
                }
            }
        },
        "/comments/{postID}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get Post Comments",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Get Post Comments",
                "operationId": "get-post-comments",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "post identifier",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/posts.getCommentsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Add comment to a post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Create post comment",
                "operationId": "create-comment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "post identifier",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "create a new comment",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/posts.createCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/posts.createCommentResponse"
                        }
                    }
                }
            }
        },
        "/follow/{businessID}": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Follow a business",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Relationships"
                ],
                "summary": "Follow business",
                "operationId": "follow-business",
                "parameters": [
                    {
                        "type": "string",
                        "description": "business user identifier",
                        "name": "businessID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/relationships.followerResponse"
                        }
                    }
                }
            }
        },
        "/followers": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get businesses' followers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Relationships"
                ],
                "summary": "Get followers",
                "operationId": "get-followers",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/relationships.getCustomersResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "security": [
                    {
                        "Auth-Token": []
                    }
                ],
                "description": "Login a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User login",
                "operationId": "login",
                "parameters": [
                    {
                        "description": "Login user",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.loginUserResponse"
                        }
                    }
                }
            }
        },
        "/lovedones": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get user's loved ones",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Relationships"
                ],
                "summary": "Get loved ones",
                "operationId": "get-loved-ones",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/relationships.getCustomersResponse"
                        }
                    }
                }
            }
        },
        "/lovedones/discover": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Discover loved ones",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Relationships"
                ],
                "summary": "Discover loved ones",
                "operationId": "discover-loved-ones",
                "parameters": [
                    {
                        "description": "contacts",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/relationships.discoverLovedOnesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/relationships.discoverLovedOnesResponse"
                        }
                    }
                }
            }
        },
        "/lovedones/{userID}": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Become a loved one",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Relationships"
                ],
                "summary": "Become a loved one",
                "operationId": "become-a-loved-one",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user identifier",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/relationships.followerResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Remove user's loved one",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Relationships"
                ],
                "summary": "Remove loved one",
                "operationId": "remove-loved-one",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user identifier",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/relationships.followerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/otp/resend": {
            "post": {
                "description": "Resend OTP code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OTP"
                ],
                "summary": "Resend OTP",
                "operationId": "resend-otp",
                "parameters": [
                    {
                        "description": "Resend OTP",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.resendOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.resendOTPResponse"
                        }
                    }
                }
            }
        },
        "/posts": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get session user's posts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Get Posts",
                "operationId": "get-posts",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/posts.getPostsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Create Post",
                "operationId": "create-post",
                "parameters": [
                    {
                        "description": "create a new post",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/posts.createPostRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/posts.createPostResponse"
                        }
                    }
                }
            }
        },
        "/posts/feed": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get session user's feed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Get Posts Feed",
                "operationId": "get-posts-feed",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/posts.getFeedResponse"
                        }
                    }
                }
            }
        },
        "/posts/reactions/{postID}": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Add reaction to a post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Add reaction to a post",
                "operationId": "add-post-reaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "post identifier",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "add a new reaction",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/posts.addReactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/posts.addReactionResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Remove reaction from a post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Remove reaction",
                "operationId": "delete-post-reaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "post identifier",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/posts.addReactionResponse"
                        }
                    }
                }
            }
        },
        "/posts/report/{postID}": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Report a post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Report post",
                "operationId": "report-post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "post identifier",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/posts.reportPostResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/posts/{postID}": {
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Delete a post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Delete Post",
                "operationId": "delete-post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "post identifier",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/posts.deletePostResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/posts/{userID}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get user's posts by user ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Get User Posts by ID",
                "operationId": "get-user-posts",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "user identifier",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/posts.getPostsResponse"
                        }
                    }
                }
            }
        },
        "/register/business": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Complete business registration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Complete business registration",
                "operationId": "register-business",
                "parameters": [
                    {
                        "description": "Complete a new business registration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.registerBusinessRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.registerResponse"
                        }
                    }
                }
            }
        },
        "/register/initialise": {
            "post": {
                "security": [
                    {
                        "Auth-Token": []
                    }
                ],
                "description": "Begin registration process",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Initialise Registration",
                "operationId": "initialise-register",
                "parameters": [
                    {
                        "description": "begin a new registration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.initialiseRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth.initialiseRegisterResponse"
                        }
                    }
                }
            }
        },
        "/register/user": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Complete a user's registration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Complete User Registration",
                "operationId": "register-user",
                "parameters": [
                    {
                        "description": "complete user registration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.registerUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.registerResponse"
                        }
                    }
                }
            }
        },
        "/register/validate": {
            "post": {
                "security": [
                    {
                        "Auth-Token": []
                    }
                ],
                "description": "Validate registration OTP",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Validate Registration OTP",
                "operationId": "validate-register-otp",
                "parameters": [
                    {
                        "description": "otp validation body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.validateOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.validateOTPResponse"
                        }
                    }
                }
            }
        },
        "/unfollow/{businessID}": {
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Unfollow a business",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Relationships"
                ],
                "summary": "Unfollow business",
                "operationId": "unfollow-business",
                "parameters": [
                    {
                        "type": "string",
                        "description": "business user identifier",
                        "name": "businessID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/relationships.followerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Edit user's profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Edit user info",
                "operationId": "edit-user",
                "parameters": [
                    {
                        "description": "edit user information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.editUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.editUserResponse"
                        }
                    }
                }
            }
        },
        "/users/notification/token": {
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "update user notification token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update user device token",
                "operationId": "update-device-token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user identifier",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.getUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{userID}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get user profile info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user",
                "operationId": "get-user-info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user identifier",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.getUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.authRequest": {
            "type": "object",
            "required": [
                "client_id",
                "secret"
            ],
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "abcede"
                },
                "secret": {
                    "type": "string",
                    "example": "password"
                }
            }
        },
        "auth.authResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "auth.createRequest": {
            "type": "object",
            "required": [
                "client_id",
                "client_name",
                "secret"
            ],
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "abcede"
                },
                "client_name": {
                    "type": "string",
                    "example": "Celebut iOS"
                },
                "secret": {
                    "type": "string",
                    "example": "password"
                }
            }
        },
        "auth.createResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "auth.initialiseRegisterRequest": {
            "type": "object",
            "required": [
                "account_type"
            ],
            "properties": {
                "account_type": {
                    "type": "integer",
                    "example": 1
                },
                "email": {
                    "type": "string",
                    "example": "user@email.com"
                },
                "phone_number": {
                    "type": "string",
                    "example": "0712345678"
                }
            }
        },
        "auth.initialiseRegisterResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "auth.loginRequest": {
            "type": "object",
            "required": [
                "account_type",
                "email",
                "password"
            ],
            "properties": {
                "account_type": {
                    "type": "integer",
                    "example": 1
                },
                "email": {
                    "type": "string",
                    "example": "user@email.com"
                },
                "password": {
                    "type": "string",
                    "example": "password"
                }
            }
        },
        "auth.loginUserResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dtos.User"
                }
            }
        },
        "auth.registerBusinessRequest": {
            "type": "object",
            "required": [
                "business_name",
                "industry_type",
                "password"
            ],
            "properties": {
                "business_name": {
                    "type": "string",
                    "example": "John XYZ Plc"
                },
                "country_code": {
                    "type": "string",
                    "example": "234"
                },
                "email": {
                    "type": "string",
                    "example": "business@email.com"
                },
                "industry_type": {
                    "type": "integer",
                    "example": 1
                },
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "phone_number": {
                    "type": "string",
                    "example": "0712345678"
                }
            }
        },
        "auth.registerResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dtos.User"
                }
            }
        },
        "auth.registerUserRequest": {
            "type": "object",
            "required": [
                "dob",
                "first_name",
                "last_name",
                "password",
                "username"
            ],
            "properties": {
                "country_code": {
                    "type": "string",
                    "example": "234"
                },
                "dob": {
                    "type": "string",
                    "example": "2020-10-12"
                },
                "email": {
                    "type": "string",
                    "example": "user@email.com"
                },
                "first_name": {
                    "type": "string",
                    "example": "John"
                },
                "gender": {
                    "type": "string",
                    "example": "male"
                },
                "interests": {
                    "type": "string",
                    "example": "fashion,entertainment"
                },
                "last_name": {
                    "type": "string",
                    "example": "Doe"
                },
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "phone_number": {
                    "type": "string",
                    "example": "0712345678"
                },
                "profile_image": {
                    "type": "string",
                    "format": "base64"
                },
                "relationship_status": {
                    "type": "string",
                    "example": "single"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "auth.validateOTPRequest": {
            "type": "object",
            "required": [
                "otp"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@email.com"
                },
                "otp": {
                    "type": "string",
                    "example": "123456"
                },
                "phone_number": {
                    "type": "string",
                    "example": "0712345678"
                }
            }
        },
        "auth.validateOTPResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "business.createIndustryRequest": {
            "type": "object",
            "required": [
                "description",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "description"
                },
                "name": {
                    "type": "string",
                    "example": "Engineering"
                }
            }
        },
        "business.getIndustryResponse": {
            "type": "object",
            "properties": {
                "industries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.Industry"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "celebrations.GetCelebrationsType": {
            "type": "string",
            "enum": [
                "recent",
                "around-you",
                "loved-ones"
            ],
            "x-enum-varnames": [
                "Recent",
                "AroundYou",
                "LovedOnes"
            ]
        },
        "celebrations.createCelebrationRequest": {
            "type": "object",
            "properties": {
                "caption": {
                    "type": "string",
                    "example": "celebration caption"
                },
                "media": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "celebrations.createCelebrationResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dtos.Celebration"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "celebrations.deleteCelebrationResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "celebrations.getCelebrationsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dtos.PagedCelebrations"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "celebrations.reportCelebrationResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dtos.AccountType": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dtos.Celebration": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/dtos.UserInfo"
                },
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.CelebrationComment"
                    }
                },
                "comments_count": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "media": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.PostMedia"
                    }
                },
                "message": {
                    "type": "string"
                },
                "post_id": {
                    "type": "string"
                },
                "reactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.UserReaction"
                    }
                },
                "reactions_count": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dtos.CelebrationComment": {
            "type": "object"
        },
        "dtos.Industry": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dtos.IndustryType": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dtos.PagedCelebrations": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.Celebration"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                }
            }
        },
        "dtos.PagedPosts": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.Post"
                    }
                }
            }
        },
        "dtos.PagedRelationships": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.UserInfo"
                    }
                }
            }
        },
        "dtos.Post": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/dtos.UserInfo"
                },
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.Post"
                    }
                },
                "comments_count": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "media": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.PostMedia"
                    }
                },
                "message": {
                    "type": "string"
                },
                "post_id": {
                    "type": "string"
                },
                "reactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.UserReaction"
                    }
                },
                "reactions_count": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dtos.PostMedia": {
            "type": "object",
            "properties": {
                "alternate_text": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "dtos.User": {
            "type": "object",
            "properties": {
                "account_type": {
                    "$ref": "#/definitions/dtos.AccountType"
                },
                "business_name": {
                    "type": "string"
                },
                "country_code": {
                    "type": "string"
                },
                "dob": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "industry_type": {
                    "$ref": "#/definitions/dtos.IndustryType"
                },
                "interests": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "profile_image": {
                    "type": "string"
                },
                "relationship_status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dtos.UserInfo": {
            "type": "object",
            "properties": {
                "business_name": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "is_verified": {
                    "type": "boolean"
                },
                "last_name": {
                    "type": "string"
                },
                "profile_image": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dtos.UserProfile": {
            "type": "object",
            "properties": {
                "account_type": {
                    "$ref": "#/definitions/dtos.AccountType"
                },
                "bio": {
                    "type": "string"
                },
                "businesses_count": {
                    "type": "integer"
                },
                "celebrations_count": {
                    "type": "integer"
                },
                "contents_count": {
                    "type": "integer"
                },
                "country_code": {
                    "type": "string"
                },
                "customers_count": {
                    "type": "integer"
                },
                "dob": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "interests": {
                    "type": "string"
                },
                "is_verified": {
                    "type": "boolean"
                },
                "last_name": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "loved_ones_count": {
                    "type": "integer"
                },
                "phone_number": {
                    "type": "string"
                },
                "profile_image": {
                    "type": "string"
                },
                "relationship_status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dtos.UserReaction": {
            "type": "object",
            "properties": {
                "reaction": {
                    "type": "string"
                }
            }
        },
        "handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "developer_information": {
                    "type": "string",
                    "example": "an error occurred"
                },
                "error": {
                    "type": "string",
                    "example": "message"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "handlers.editUserRequest": {
            "type": "object",
            "required": [
                "dob",
                "first_name",
                "last_name",
                "password",
                "username"
            ],
            "properties": {
                "country_code": {
                    "type": "string",
                    "example": "234"
                },
                "dob": {
                    "type": "string",
                    "example": "2020-10-12"
                },
                "email": {
                    "type": "string",
                    "example": "user@email.com"
                },
                "first_name": {
                    "type": "string",
                    "example": "John"
                },
                "last_name": {
                    "type": "string",
                    "example": "Doe"
                },
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "phone_number": {
                    "type": "string",
                    "example": "0712345678"
                },
                "profile_image": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "handlers.editUserResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dtos.User"
                }
            }
        },
        "handlers.getUserResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dtos.UserProfile"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "handlers.resendOTPRequest": {
            "type": "object",
            "required": [
                "mode"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@email.com"
                },
                "mode": {
                    "type": "string",
                    "example": "register"
                },
                "phone_number": {
                    "type": "string",
                    "example": "0712345678"
                }
            }
        },
        "handlers.resendOTPResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.Industry": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "example": "entertainment"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "posts.addReactionRequest": {
            "type": "object",
            "properties": {
                "reaction": {
                    "type": "string",
                    "example": "emoji"
                }
            }
        },
        "posts.addReactionResponse": {
            "type": "object",
            "properties": {
                "post": {
                    "$ref": "#/definitions/dtos.Post"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "posts.createCommentRequest": {
            "type": "object",
            "properties": {
                "media": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "What is happening?"
                }
            }
        },
        "posts.createCommentResponse": {
            "type": "object",
            "properties": {
                "post": {
                    "$ref": "#/definitions/dtos.Post"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "posts.createPostRequest": {
            "type": "object",
            "properties": {
                "media": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "What is happening?"
                }
            }
        },
        "posts.createPostResponse": {
            "type": "object",
            "properties": {
                "post": {
                    "$ref": "#/definitions/dtos.Post"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "posts.deletePostResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "posts.getCommentData": {
            "type": "object",
            "properties": {
                "comments": {
                    "$ref": "#/definitions/dtos.PagedPosts"
                },
                "post": {
                    "$ref": "#/definitions/dtos.Post"
                }
            }
        },
        "posts.getCommentsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/posts.getCommentData"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "posts.getFeedResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dtos.PagedPosts"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "posts.getPostsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dtos.PagedPosts"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "posts.reportPostResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "relationships.discoverLovedOnesRequest": {
            "type": "object",
            "properties": {
                "contacts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "relationships.discoverLovedOnesResponse": {
            "type": "object",
            "properties": {
                "contacts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.UserInfo"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "relationships.followerResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "relationships.getCustomersResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dtos.PagedRelationships"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Auth-Token": {
            "description": "Type token for unauthenticated requests",
            "type": "apiKey",
            "name": "x-auth-token",
            "in": "header"
        },
        "Bearer": {
            "description": "` + "`" + `Bearer token` + "`" + ` for authenticated requests",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8083",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Celebut API",
	Description:      "Celebut Backend REST endpoints",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
