// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/business/industry": {
            "get": {
                "description": "Get list of business industries",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Industries"
                ],
                "summary": "Get industries",
                "operationId": "industries-list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "x-auth-token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/business.getIndustryResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new business industry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Industries"
                ],
                "summary": "Create industry",
                "operationId": "create-industry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "x-auth-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create new industry",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/business.createIndustryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Industry"
                        }
                    }
                }
            }
        },
        "/celebrations": {
            "get": {
                "description": "Get user's celebrations",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Celebrations"
                ],
                "summary": "Get Celebrations",
                "operationId": "get-celebrations",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.getCelebrationResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a celebration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Celebrations"
                ],
                "summary": "Create Celebration",
                "operationId": "create-celebration",
                "parameters": [
                    {
                        "description": "create a new celebration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.createCelebrationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.createCelebrationResponse"
                        }
                    }
                }
            }
        },
        "/celebrations/{celebrationID}": {
            "delete": {
                "description": "Delete a celebration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Celebrations"
                ],
                "summary": "Delete Celebration",
                "operationId": "delete-celebration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "celebration post identifier",
                        "name": "celebrationID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.deleteCelebrationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/client": {
            "post": {
                "description": "Create a new client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "[Admin] Create a client",
                "operationId": "create-client",
                "parameters": [
                    {
                        "description": "Create a client",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.createRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.createResponse"
                        }
                    }
                }
            }
        },
        "/client/auth": {
            "post": {
                "description": "Authenticate a client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Authenticate a client",
                "operationId": "auth-client",
                "parameters": [
                    {
                        "description": "Authenticate a client",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.authRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.authResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Login a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User login",
                "operationId": "login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "x-auth-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Login user",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.loginBusinessResponse"
                        }
                    }
                }
            }
        },
        "/register/business": {
            "post": {
                "description": "Register a business",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Business Register",
                "operationId": "register-business",
                "parameters": [
                    {
                        "description": "Registers a new business",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.registerBusinessRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterBusinessResponse"
                        }
                    }
                }
            }
        },
        "/register/user": {
            "post": {
                "description": "Register a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User Register",
                "operationId": "register-user",
                "parameters": [
                    {
                        "description": "Registers a new user",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.registerUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.RegisterBusinessResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dtos.Business"
                }
            }
        },
        "auth.RegisterResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dtos.User"
                }
            }
        },
        "auth.authRequest": {
            "type": "object",
            "required": [
                "client_id",
                "secret"
            ],
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "abcede"
                },
                "secret": {
                    "type": "string",
                    "example": "password"
                }
            }
        },
        "auth.authResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "auth.createRequest": {
            "type": "object",
            "required": [
                "client_id",
                "client_name",
                "secret"
            ],
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "abcede"
                },
                "client_name": {
                    "type": "string",
                    "example": "Celebut iOS"
                },
                "secret": {
                    "type": "string",
                    "example": "password"
                }
            }
        },
        "auth.createResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "auth.loginBusinessResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dtos.Business"
                }
            }
        },
        "auth.loginRequest": {
            "type": "object",
            "required": [
                "account_type",
                "email",
                "password"
            ],
            "properties": {
                "account_type": {
                    "type": "integer",
                    "example": 1
                },
                "email": {
                    "type": "string",
                    "example": "user@email.com"
                },
                "password": {
                    "type": "string",
                    "example": "password"
                }
            }
        },
        "auth.loginUserResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dtos.User"
                }
            }
        },
        "auth.registerBusinessRequest": {
            "type": "object",
            "required": [
                "business_name",
                "country_code",
                "email",
                "industry_type",
                "password",
                "phone_number"
            ],
            "properties": {
                "business_name": {
                    "type": "string",
                    "example": "John XYZ Plc"
                },
                "country_code": {
                    "type": "string",
                    "example": "234"
                },
                "email": {
                    "type": "string",
                    "example": "user@email.com"
                },
                "industry_type": {
                    "type": "integer",
                    "example": 1
                },
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "phone_number": {
                    "type": "string",
                    "example": "0712345678"
                }
            }
        },
        "auth.registerUserRequest": {
            "type": "object",
            "required": [
                "country_code",
                "dob",
                "email",
                "first_name",
                "gender",
                "interests",
                "last_name",
                "password",
                "phone_number",
                "relationship_status",
                "username"
            ],
            "properties": {
                "country_code": {
                    "type": "string",
                    "example": "234"
                },
                "dob": {
                    "type": "string",
                    "example": "2020-10-12"
                },
                "email": {
                    "type": "string",
                    "example": "user@email.com"
                },
                "first_name": {
                    "type": "string",
                    "example": "John"
                },
                "gender": {
                    "type": "string",
                    "example": "male"
                },
                "interests": {
                    "type": "string",
                    "example": "fashion,entertainment"
                },
                "last_name": {
                    "type": "string",
                    "example": "Doe"
                },
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "phone_number": {
                    "type": "string",
                    "example": "0712345678"
                },
                "relationship_status": {
                    "type": "string",
                    "example": "single"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "business.createIndustryRequest": {
            "type": "object",
            "required": [
                "description",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "en"
                },
                "name": {
                    "type": "string",
                    "example": "auto"
                }
            }
        },
        "business.getIndustryResponse": {
            "type": "object",
            "properties": {
                "industries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Industry"
                    }
                }
            }
        },
        "dtos.Business": {
            "type": "object",
            "properties": {
                "business_name": {
                    "type": "string"
                },
                "country_code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "industry_type": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dtos.Celebration": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dtos.User"
                }
            }
        },
        "dtos.User": {
            "type": "object",
            "properties": {
                "country_code": {
                    "type": "string"
                },
                "dob": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "interests": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "relationship_status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "message"
                }
            }
        },
        "handlers.createCelebrationRequest": {
            "type": "object",
            "required": [
                "celebrations",
                "message"
            ],
            "properties": {
                "celebrations": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "What is happening?"
                }
            }
        },
        "handlers.createCelebrationResponse": {
            "type": "object"
        },
        "handlers.deleteCelebrationResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "handlers.getCelebrationResponse": {
            "type": "object",
            "properties": {
                "celebrations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.Celebration"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                }
            }
        },
        "models.Industry": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "example": "entertainment"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8083",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Celebut API",
	Description:      "Celebut Backend REST endpoints",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
