// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/business/industry": {
            "get": {
                "description": "Get list of business industries",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Industries"
                ],
                "summary": "Get industries",
                "operationId": "industries-list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "x-auth-token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/business.getIndustryResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new business industry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Industries"
                ],
                "summary": "Create industry",
                "operationId": "create-industry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "x-auth-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create new industry",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/business.createIndustryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/business.Industry"
                        }
                    }
                }
            }
        },
        "/client": {
            "post": {
                "description": "Create a new client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "Create a client",
                "operationId": "create-client",
                "parameters": [
                    {
                        "description": "Create a client",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.createRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.createResponse"
                        }
                    }
                }
            }
        },
        "/client/auth": {
            "post": {
                "description": "Authenticate a client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Authenticate a client",
                "operationId": "auth-client",
                "parameters": [
                    {
                        "description": "Authenticate a client",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.authRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.authResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Login a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User login",
                "operationId": "login",
                "parameters": [
                    {
                        "description": "Login user",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Register a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User Register",
                "operationId": "register",
                "parameters": [
                    {
                        "description": "Registers a new user",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.RegisterResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/users.User"
                }
            }
        },
        "auth.authRequest": {
            "type": "object",
            "required": [
                "client_id",
                "secret"
            ],
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "abcede"
                },
                "secret": {
                    "type": "string",
                    "example": "password"
                }
            }
        },
        "auth.authResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "auth.createRequest": {
            "type": "object",
            "required": [
                "client_id",
                "client_name",
                "secret"
            ],
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "abcede"
                },
                "client_name": {
                    "type": "string",
                    "example": "Celebut iOS"
                },
                "secret": {
                    "type": "string",
                    "example": "password"
                }
            }
        },
        "auth.createResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "auth.registerRequest": {
            "type": "object",
            "required": [
                "account_type",
                "email",
                "password"
            ],
            "properties": {
                "account_type": {
                    "type": "integer",
                    "example": 1
                },
                "email": {
                    "type": "string",
                    "example": "user@email.com"
                },
                "password": {
                    "type": "string",
                    "example": "password"
                }
            }
        },
        "business.Industry": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "example": "entertainment"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "business.createIndustryRequest": {
            "type": "object",
            "required": [
                "description",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "en"
                },
                "name": {
                    "type": "string",
                    "example": "auto"
                }
            }
        },
        "business.getIndustryResponse": {
            "type": "object",
            "properties": {
                "industries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/business.Industry"
                    }
                }
            }
        },
        "users.User": {
            "type": "object",
            "properties": {
                "countryCode": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "dateOfBirth": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "interests": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "passwordHash": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "relationshipStatus": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8083",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Celebut API",
	Description:      "Celebut Backend REST endpoints",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
