basePath: /v1
definitions:
  auth.RegisterBusinessResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/dtos.Business'
    type: object
  auth.RegisterResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/dtos.User'
    type: object
  auth.authRequest:
    properties:
      client_id:
        example: abcede
        type: string
      secret:
        example: password
        type: string
    required:
    - client_id
    - secret
    type: object
  auth.authResponse:
    properties:
      token:
        type: string
    type: object
  auth.createRequest:
    properties:
      client_id:
        example: abcede
        type: string
      client_name:
        example: Celebut iOS
        type: string
      secret:
        example: password
        type: string
    required:
    - client_id
    - client_name
    - secret
    type: object
  auth.createResponse:
    properties:
      message:
        type: string
    type: object
  auth.loginBusinessResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/dtos.Business'
    type: object
  auth.loginRequest:
    properties:
      account_type:
        example: 1
        type: integer
      email:
        example: user@email.com
        type: string
      password:
        example: password
        type: string
    required:
    - account_type
    - email
    - password
    type: object
  auth.loginUserResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/dtos.User'
    type: object
  auth.registerBusinessRequest:
    properties:
      business_name:
        example: John XYZ Plc
        type: string
      country_code:
        example: "234"
        type: string
      email:
        example: user@email.com
        type: string
      industry_type:
        example: 1
        type: integer
      password:
        example: password
        type: string
      phone_number:
        example: "0712345678"
        type: string
    required:
    - business_name
    - country_code
    - email
    - industry_type
    - password
    - phone_number
    type: object
  auth.registerUserRequest:
    properties:
      country_code:
        example: "234"
        type: string
      dob:
        example: "2020-10-12"
        type: string
      email:
        example: user@email.com
        type: string
      first_name:
        example: John
        type: string
      gender:
        example: male
        type: string
      interests:
        example: fashion,entertainment
        type: string
      last_name:
        example: Doe
        type: string
      password:
        example: password
        type: string
      phone_number:
        example: "0712345678"
        type: string
      relationship_status:
        example: single
        type: string
      username:
        example: johndoe
        type: string
    required:
    - country_code
    - dob
    - email
    - first_name
    - gender
    - interests
    - last_name
    - password
    - phone_number
    - relationship_status
    - username
    type: object
  business.createIndustryRequest:
    properties:
      description:
        example: en
        type: string
      name:
        example: auto
        type: string
    required:
    - description
    - name
    type: object
  business.getIndustryResponse:
    properties:
      industries:
        items:
          $ref: '#/definitions/models.Industry'
        type: array
    type: object
  dtos.Business:
    properties:
      business_name:
        type: string
      country_code:
        type: string
      email:
        type: string
      industry_type:
        type: string
      phone_number:
        type: string
      user_id:
        type: string
    type: object
  dtos.Celebration:
    properties:
      created_at:
        type: string
      message:
        type: string
      updated_at:
        type: string
      user:
        $ref: '#/definitions/dtos.User'
    type: object
  dtos.User:
    properties:
      country_code:
        type: string
      dob:
        type: string
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      interests:
        type: string
      last_name:
        type: string
      phone_number:
        type: string
      relationship_status:
        type: string
      user_id:
        type: string
      username:
        type: string
    type: object
  handlers.ErrorResponse:
    properties:
      error:
        example: message
        type: string
    type: object
  handlers.createCelebrationRequest:
    properties:
      celebrations:
        items:
          type: object
        type: array
      message:
        example: What is happening?
        type: string
    required:
    - celebrations
    - message
    type: object
  handlers.createCelebrationResponse:
    type: object
  handlers.deleteCelebrationResponse:
    properties:
      message:
        type: string
    type: object
  handlers.getCelebrationResponse:
    properties:
      celebrations:
        items:
          $ref: '#/definitions/dtos.Celebration'
        type: array
      limit:
        type: integer
      page:
        type: integer
    type: object
  models.Industry:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        example: entertainment
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8083
info:
  contact: {}
  description: Celebut Backend REST endpoints
  title: Celebut API
  version: "1.0"
paths:
  /business/industry:
    get:
      consumes:
      - application/json
      description: Get list of business industries
      operationId: industries-list
      parameters:
      - description: Authorization Token
        in: header
        name: x-auth-token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/business.getIndustryResponse'
      summary: Get industries
      tags:
      - Industries
    post:
      consumes:
      - application/json
      description: Create a new business industry
      operationId: create-industry
      parameters:
      - description: Authorization Token
        in: header
        name: x-auth-token
        required: true
        type: string
      - description: Create new industry
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/business.createIndustryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Industry'
      summary: Create industry
      tags:
      - Industries
  /celebrations:
    get:
      consumes:
      - application/json
      description: Get user's celebrations
      operationId: get-celebrations
      parameters:
      - in: query
        name: limit
        type: integer
      - in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.getCelebrationResponse'
      summary: Get Celebrations
      tags:
      - Celebrations
    post:
      consumes:
      - application/json
      description: Create a celebration
      operationId: create-celebration
      parameters:
      - description: create a new celebration
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.createCelebrationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.createCelebrationResponse'
      summary: Create Celebration
      tags:
      - Celebrations
  /celebrations/{celebrationID}:
    delete:
      consumes:
      - application/json
      description: Delete a celebration
      operationId: delete-celebration
      parameters:
      - description: celebration post identifier
        in: path
        name: celebrationID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.deleteCelebrationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Delete Celebration
      tags:
      - Celebrations
  /client:
    post:
      consumes:
      - application/json
      description: Create a new client
      operationId: create-client
      parameters:
      - description: Create a client
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.createRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.createResponse'
      summary: '[Admin] Create a client'
      tags:
      - Client
  /client/auth:
    post:
      consumes:
      - application/json
      description: Authenticate a client
      operationId: auth-client
      parameters:
      - description: Authenticate a client
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.authRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.authResponse'
      summary: Authenticate a client
      tags:
      - Authentication
  /login:
    post:
      consumes:
      - application/json
      description: Login a user
      operationId: login
      parameters:
      - description: Authorization Token
        in: header
        name: x-auth-token
        required: true
        type: string
      - description: Login user
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.loginBusinessResponse'
      summary: User login
      tags:
      - Authentication
  /register/business:
    post:
      consumes:
      - application/json
      description: Register a business
      operationId: register-business
      parameters:
      - description: Registers a new business
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.registerBusinessRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/auth.RegisterBusinessResponse'
      summary: Business Register
      tags:
      - Authentication
  /register/user:
    post:
      consumes:
      - application/json
      description: Register a user
      operationId: register-user
      parameters:
      - description: Registers a new user
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.registerUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/auth.RegisterResponse'
      summary: User Register
      tags:
      - Authentication
swagger: "2.0"
